### ISSUE TITLE
Add AUMS support

### ISSUE THREAD

**Issue by rajkumaar23** [rajkumaar23/amritarepo-bot#11]
AUMS API Reference : https://github.com/rajkumaar23/amrita-repository/tree/master/app/src/main/java/in/co/rajkumaar/amritarepo/aumsV2
# Workflow : 
- /ums - Display Menu for /ums_attendance, /ums_marks
- If any of those two is the command, should check if user is logged in already
otherwise ask user for login `/ums_login_username:password `
- When trying to login, call the AUMS login API, get his access token and store it encrypted in a local JSON file as 
```json
{ 
  "telegramID1" : { "aumsToken" : "the token received after login" }, 
  "telegramID2" : { "aumsToken" : "the token received after login" } 
}
``` 
- [Encrypt/decrypt](https://www.geeksforgeeks.org/how-to-encrypt-and-decrypt-a-php-string/) the tokens using a secret key which can be stored in config.php
- Then whenever attendance or marks is called, you can decrypt access token from local JSON for that particular user and then call the AUMS ATTENDANCE/MARKS API...that can be designed as u wish
- /ums_logout should remove the entry from local JSON

**Comment by ArunVigesh** [comment]
Will do it 👍
