### ISSUE TITLE
/ft <keyword> returns no results

### ISSUE THREAD

**Issue by radiantly** [rajkumaar23/amritarepo-bot#16]
If the command is given to the bot is `/ft <keyword>`, it returns no results.

E.g.
![image](https://user-images.githubusercontent.com/44368997/83322163-0b22f300-a273-11ea-8673-a0be00c8f0f0.png)
It looks like that this is caused by a space prepended to the search term.

**Comment by rajkumaar23** [comment]
@radiantly Thanks for reporting! Have fixed the issue. Kindly verify.

**Comment by radiantly** [comment]
Thanks, works now! :+1:
